# Setup
title:               Zhengsong Huang
tagline:             'QAQ'
description:         'Hope is a good thing, maybe the best of things. And no good thing ever dies.'
url:
baseurl:             ''
paginate:            10
paginate_path:       '/blogs/page:num'
permalink:           pretty
# timezone:            Asia/Shanghai

# About/contact
author:
  name:              Wilson Huang
  url:               https://github.com/Wilsooon
  email:             huangzhs8@mail2.sysu.edu.cn

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

encoding: utf-8
highlighter: rouge
minima:
  date_format: "%b %-d, %Y"

# theme: minima
